### ISSUE TITLE
live-factory with local ffmpeg

### ISSUE THREAD

**Issue by sfahadshahzad** [olzzon/live-factory#1]
Hi Kasper,

I Would like to express my gratitude for your contributions to the open-source community. Thank you for your valuable work.

Could you provide instructions on setting up a live-factory with local ffmpeg, including decklink and NDI support?

My current OS Ubuntu 22.04.

Regards,

Fahad

**Comment by olzzon** [comment]
You will need a running build of ffmpeg.
In the Readme there's a how to build that, regarding NDI support there's a link to a patch at the end of the readme.

The main focus of this project will however be docker, and may require some skills to setup.

How this helps you
:) Kasper

**Comment by sfahadshahzad** [comment]
I've successfully compiled ffmpeg with decklink and SRT support on my local system, and I also have a functional Docker container with these configurations.

Regards,

Fahad

**Comment by sfahadshahzad** [comment]
local ffmpeg works fine but I am not able to use docker node.

Fahad

**Comment by olzzon** [comment]
You have to enable the Docker API on the docker host machine.

**Comment by olzzon** [comment]
@sfahadshahzad : https://medium.com/@ssmak/how-to-enable-docker-remote-api-on-docker-host-7b73bd3278c6
